# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Spalmalo
email: office@spalmalo.com
description: > # this means to ignore newlines until "baseurl:"
  Spalmalo - это место, где ваши идеи воплощаются в реальность от задумки до реализации.
  Для нас не бывает неважных мелочей, каждая задача становится своеобразной вершиной,
  которую мы смело покоряем. Наши дизайнеры мастерски владеют игрой со шрифтами,
  разработчики - полиглоты, понимающие любой язык с полусимвола,
  а прожект-менеджеры обладают поистине безграничным терпением.
  Мы просто любим свою работу и производим хороший продукт.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://spalmalo.com" # the base hostname & protocol for your site
twitter_username: spalmalo
github_username:  spalmalo

# Build settings
markdown: kramdown
